- title: Web
  icon: basic-laptop
  content: 企业级网站设计、开发、运行，维护
- title: App
  icon: basic-smartphone
  content: 移动端HTML5应用开发
- title: 微信
  icon: basic-message-multiple
  content: 微信服务号、微信商城、微信小程序等微信内部Web应用的设计开发与维护